
version: "2"

networks:
  internal:
    driver: bridge

services:
  cloudflare-ddns:
      image: oznu/cloudflare-ddns:latest
      restart: always
      networks:
        - internal
      environment:
        - API_KEY=${APICLOUNDFLARE}
        - ZONE=${DOMAIN}                                        
        - PROXIED=true